videl_gallery_homepage:
    pattern:  /
    defaults: { _controller: VidelGalleryBundle:Default:index }

videl_gallery_image_search:
    pattern: /search/image/{var}
    defaults: { _controller:VidelGalleryBundle:Default:searchImage }

VidelGalleryBundle_image_crud:
    resource: "@VidelGalleryBundle/Resources/config/routing/image.yml"
    prefix:	/image_crud

VidelGalleryBundle_gallery_crud:
    resource: "@VidelGalleryBundle/Resources/config/routing/gallery.yml"
    prefix: /gallery_crud