parameters:
#    videl_gallery.example.class: Videl\VidelGalleryBundle\Example

services:
#    videl_gallery.example:
#        class: %videl_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
